### PR TITLE
Release

### PR DESCRIPTION
**Pull request by Victorius**
## Proposed changes

- added support adaptive layout;
- fixed bug with link in configuration;
- added description how to connect wallet;
- fixed issue with default slippage value;
- fixed issue string on pop up window of wallet connect.

## Types of changes

- [x] Bugfix
- [ ] New feature or Enhancement
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-dex-frontend/dev/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-dex-frontend)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you proposed and what alternatives you have considered, etc.

### CODE REVIEW

**Review by 0xxlegolas — APPROVED** [review]

**Comment by Victorius** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by WRRicht3r** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by WRRicht3r** [comment]
Recheck

**Comment by Sociopacific** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xxlegolas** [comment]
Recheck

**Comment by 0xxlegolas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xxlegolas** [comment]
Recheck

**Comment by 0x009922** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xxlegolas** [comment]
Recheck

**Pull request merged**
